"""Constants for Family Intercom."""

DOMAIN = "family_intercom"
PANEL_URL_PATH = "family-intercom"
STATIC_URL = "/family_intercom_static"
FRONTEND_MODULE = "family-intercom-panel-v9.js"
INTEGRATION_VERSION = "0.5.4"
DEFAULT_TTS_ENTITY = "tts.home_assistant_cloud"
DEFAULT_CLEANUP_SECONDS = 120
DEFAULT_SHOW_SIDEBAR = True
DEFAULT_CHIME_ENABLED = True
DEFAULT_VOLUME_ENABLED = False
DEFAULT_VOLUME_LEVEL = 0.55
DEFAULT_RESTORE_SECONDS = 10
DEFAULT_QUIET_HOURS_ENABLED = False
DEFAULT_QUIET_START = "22:00"
DEFAULT_QUIET_END = "07:00"
DEFAULT_AUTO_REPLY_VIEW_ENABLED = False
DEFAULT_REPLY_DASHBOARD_PATH = "lovelace"
DEFAULT_REPLY_VIEW_PATH = "family-intercom-reply"
DEFAULT_REPLY_CAST_DELAY_SECONDS = 20
